### ISSUE TITLE
Battery and Wifi are not themed with the rest of the UI

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/ShellSharp#14]
![image](https://cloud.githubusercontent.com/assets/3945538/11454421/8831c6c2-95f9-11e5-93e3-cc3f8e462a73.png)
I changed the Theme to Black Back and White Fore

**Comment by emmatyping** [comment]
Fixed. I wasn't supposed to put in the control's codebehind, but in the MenuWindow codebehind.

Note, not yet pushed.
