### ISSUE TITLE
Rename?

### ISSUE THREAD

**Issue by emmatyping** [IronManMark20/ShellSharp#16]
I am considering renaming to MetroShell or something else. Thoughts?

**Comment by Krutonium** [comment]
How about calling it IronShell?

**Comment by emmatyping** [comment]
Sure.

**Comment by Krutonium** [comment]
Excellent

**Comment by emmatyping** [comment]
I'm going to rename the solution and everything

**Comment by Krutonium** [comment]
Sounds Good
