### ISSUE TITLE
If a program opens and closes very quickly, the shell crashes outside of our code.

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/ShellSharp#5]

**Comment by emmatyping** [comment]
Could you explain what you mean by outside of our code?

**Comment by Krutonium** [comment]
VS Can't debug it, it's in one of MS's Libraries.

**Comment by emmatyping** [comment]
No exception or anything? I haven't been able to reproduce.

**Comment by Krutonium** [comment]
Nope, it was outside user code. I havn't had it happen since, sooo :)

**Comment by emmatyping** [comment]
Hoping this isn't a problem. Report if you still have it.

**Comment by Krutonium** [comment]
Will do
